(cl:defpackage task3-srv
  (:use )
  (:export
   "OBJECT_FRAME_DATA"
   "<OBJECT_FRAME_DATA-REQUEST>"
   "OBJECT_FRAME_DATA-REQUEST"
   "<OBJECT_FRAME_DATA-RESPONSE>"
   "OBJECT_FRAME_DATA-RESPONSE"
  ))

