// Generated by gencpp from file vector_msgs/JacoStatus.msg
// DO NOT EDIT!


#ifndef VECTOR_MSGS_MESSAGE_JACOSTATUS_H
#define VECTOR_MSGS_MESSAGE_JACOSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vector_msgs
{
template <class ContainerAllocator>
struct JacoStatus_
{
  typedef JacoStatus_<ContainerAllocator> Type;

  JacoStatus_()
    : header()
    , raw_joint_pos_rad()  {
    }
  JacoStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , raw_joint_pos_rad(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _raw_joint_pos_rad_type;
  _raw_joint_pos_rad_type raw_joint_pos_rad;




  typedef boost::shared_ptr< ::vector_msgs::JacoStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vector_msgs::JacoStatus_<ContainerAllocator> const> ConstPtr;

}; // struct JacoStatus_

typedef ::vector_msgs::JacoStatus_<std::allocator<void> > JacoStatus;

typedef boost::shared_ptr< ::vector_msgs::JacoStatus > JacoStatusPtr;
typedef boost::shared_ptr< ::vector_msgs::JacoStatus const> JacoStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vector_msgs::JacoStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vector_msgs::JacoStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vector_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'vector_msgs': ['/home/kristopher/vector_ws/src/vector_v1/vector_common/vector_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vector_msgs::JacoStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vector_msgs::JacoStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vector_msgs::JacoStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vector_msgs::JacoStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vector_msgs::JacoStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vector_msgs::JacoStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vector_msgs::JacoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7737d010f68dc207c2b507e374ae436";
  }

  static const char* value(const ::vector_msgs::JacoStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7737d010f68dc20ULL;
  static const uint64_t static_value2 = 0x7c2b507e374ae436ULL;
};

template<class ContainerAllocator>
struct DataType< ::vector_msgs::JacoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vector_msgs/JacoStatus";
  }

  static const char* value(const ::vector_msgs::JacoStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vector_msgs::JacoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32[] raw_joint_pos_rad\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::vector_msgs::JacoStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vector_msgs::JacoStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.raw_joint_pos_rad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JacoStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vector_msgs::JacoStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vector_msgs::JacoStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "raw_joint_pos_rad[]" << std::endl;
    for (size_t i = 0; i < v.raw_joint_pos_rad.size(); ++i)
    {
      s << indent << "  raw_joint_pos_rad[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.raw_joint_pos_rad[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VECTOR_MSGS_MESSAGE_JACOSTATUS_H
