// Generated by gencpp from file wpi_jaco_msgs/GetAngularPosition.msg
// DO NOT EDIT!


#ifndef WPI_JACO_MSGS_MESSAGE_GETANGULARPOSITION_H
#define WPI_JACO_MSGS_MESSAGE_GETANGULARPOSITION_H

#include <ros/service_traits.h>


#include <wpi_jaco_msgs/GetAngularPositionRequest.h>
#include <wpi_jaco_msgs/GetAngularPositionResponse.h>


namespace wpi_jaco_msgs
{

struct GetAngularPosition
{

typedef GetAngularPositionRequest Request;
typedef GetAngularPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAngularPosition
} // namespace wpi_jaco_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wpi_jaco_msgs::GetAngularPosition > {
  static const char* value()
  {
    return "2ddbdf76cbefd59cd9a914780fdf2963";
  }

  static const char* value(const ::wpi_jaco_msgs::GetAngularPosition&) { return value(); }
};

template<>
struct DataType< ::wpi_jaco_msgs::GetAngularPosition > {
  static const char* value()
  {
    return "wpi_jaco_msgs/GetAngularPosition";
  }

  static const char* value(const ::wpi_jaco_msgs::GetAngularPosition&) { return value(); }
};


// service_traits::MD5Sum< ::wpi_jaco_msgs::GetAngularPositionRequest> should match 
// service_traits::MD5Sum< ::wpi_jaco_msgs::GetAngularPosition > 
template<>
struct MD5Sum< ::wpi_jaco_msgs::GetAngularPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wpi_jaco_msgs::GetAngularPosition >::value();
  }
  static const char* value(const ::wpi_jaco_msgs::GetAngularPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wpi_jaco_msgs::GetAngularPositionRequest> should match 
// service_traits::DataType< ::wpi_jaco_msgs::GetAngularPosition > 
template<>
struct DataType< ::wpi_jaco_msgs::GetAngularPositionRequest>
{
  static const char* value()
  {
    return DataType< ::wpi_jaco_msgs::GetAngularPosition >::value();
  }
  static const char* value(const ::wpi_jaco_msgs::GetAngularPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wpi_jaco_msgs::GetAngularPositionResponse> should match 
// service_traits::MD5Sum< ::wpi_jaco_msgs::GetAngularPosition > 
template<>
struct MD5Sum< ::wpi_jaco_msgs::GetAngularPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wpi_jaco_msgs::GetAngularPosition >::value();
  }
  static const char* value(const ::wpi_jaco_msgs::GetAngularPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wpi_jaco_msgs::GetAngularPositionResponse> should match 
// service_traits::DataType< ::wpi_jaco_msgs::GetAngularPosition > 
template<>
struct DataType< ::wpi_jaco_msgs::GetAngularPositionResponse>
{
  static const char* value()
  {
    return DataType< ::wpi_jaco_msgs::GetAngularPosition >::value();
  }
  static const char* value(const ::wpi_jaco_msgs::GetAngularPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WPI_JACO_MSGS_MESSAGE_GETANGULARPOSITION_H
