// Generated by gencpp from file wpi_jaco_msgs/GetCartesianPositionResponse.msg
// DO NOT EDIT!


#ifndef WPI_JACO_MSGS_MESSAGE_GETCARTESIANPOSITIONRESPONSE_H
#define WPI_JACO_MSGS_MESSAGE_GETCARTESIANPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace wpi_jaco_msgs
{
template <class ContainerAllocator>
struct GetCartesianPositionResponse_
{
  typedef GetCartesianPositionResponse_<ContainerAllocator> Type;

  GetCartesianPositionResponse_()
    : pos()  {
    }
  GetCartesianPositionResponse_(const ContainerAllocator& _alloc)
    : pos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _pos_type;
  _pos_type pos;




  typedef boost::shared_ptr< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetCartesianPositionResponse_

typedef ::wpi_jaco_msgs::GetCartesianPositionResponse_<std::allocator<void> > GetCartesianPositionResponse;

typedef boost::shared_ptr< ::wpi_jaco_msgs::GetCartesianPositionResponse > GetCartesianPositionResponsePtr;
typedef boost::shared_ptr< ::wpi_jaco_msgs::GetCartesianPositionResponse const> GetCartesianPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wpi_jaco_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wpi_jaco_msgs': ['/home/kristopher/vector_ws/src/wpi_jaco_msgs/msg', '/home/kristopher/vector_ws/devel/share/wpi_jaco_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90eff4f5bd7896007c2525f114434660";
  }

  static const char* value(const ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90eff4f5bd789600ULL;
  static const uint64_t static_value2 = 0x7c2525f114434660ULL;
};

template<class ContainerAllocator>
struct DataType< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wpi_jaco_msgs/GetCartesianPositionResponse";
  }

  static const char* value(const ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist pos\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCartesianPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wpi_jaco_msgs::GetCartesianPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WPI_JACO_MSGS_MESSAGE_GETCARTESIANPOSITIONRESPONSE_H
