// Generated by gencpp from file wpi_jaco_msgs/GravComp.msg
// DO NOT EDIT!


#ifndef WPI_JACO_MSGS_MESSAGE_GRAVCOMP_H
#define WPI_JACO_MSGS_MESSAGE_GRAVCOMP_H

#include <ros/service_traits.h>


#include <wpi_jaco_msgs/GravCompRequest.h>
#include <wpi_jaco_msgs/GravCompResponse.h>


namespace wpi_jaco_msgs
{

struct GravComp
{

typedef GravCompRequest Request;
typedef GravCompResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GravComp
} // namespace wpi_jaco_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wpi_jaco_msgs::GravComp > {
  static const char* value()
  {
    return "9b3823379e0371a824478dadc91ab9ef";
  }

  static const char* value(const ::wpi_jaco_msgs::GravComp&) { return value(); }
};

template<>
struct DataType< ::wpi_jaco_msgs::GravComp > {
  static const char* value()
  {
    return "wpi_jaco_msgs/GravComp";
  }

  static const char* value(const ::wpi_jaco_msgs::GravComp&) { return value(); }
};


// service_traits::MD5Sum< ::wpi_jaco_msgs::GravCompRequest> should match 
// service_traits::MD5Sum< ::wpi_jaco_msgs::GravComp > 
template<>
struct MD5Sum< ::wpi_jaco_msgs::GravCompRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wpi_jaco_msgs::GravComp >::value();
  }
  static const char* value(const ::wpi_jaco_msgs::GravCompRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wpi_jaco_msgs::GravCompRequest> should match 
// service_traits::DataType< ::wpi_jaco_msgs::GravComp > 
template<>
struct DataType< ::wpi_jaco_msgs::GravCompRequest>
{
  static const char* value()
  {
    return DataType< ::wpi_jaco_msgs::GravComp >::value();
  }
  static const char* value(const ::wpi_jaco_msgs::GravCompRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wpi_jaco_msgs::GravCompResponse> should match 
// service_traits::MD5Sum< ::wpi_jaco_msgs::GravComp > 
template<>
struct MD5Sum< ::wpi_jaco_msgs::GravCompResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wpi_jaco_msgs::GravComp >::value();
  }
  static const char* value(const ::wpi_jaco_msgs::GravCompResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wpi_jaco_msgs::GravCompResponse> should match 
// service_traits::DataType< ::wpi_jaco_msgs::GravComp > 
template<>
struct DataType< ::wpi_jaco_msgs::GravCompResponse>
{
  static const char* value()
  {
    return DataType< ::wpi_jaco_msgs::GravComp >::value();
  }
  static const char* value(const ::wpi_jaco_msgs::GravCompResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WPI_JACO_MSGS_MESSAGE_GRAVCOMP_H
