// Generated by gencpp from file wpi_jaco_msgs/JacoFingerVel.msg
// DO NOT EDIT!


#ifndef WPI_JACO_MSGS_MESSAGE_JACOFINGERVEL_H
#define WPI_JACO_MSGS_MESSAGE_JACOFINGERVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wpi_jaco_msgs
{
template <class ContainerAllocator>
struct JacoFingerVel_
{
  typedef JacoFingerVel_<ContainerAllocator> Type;

  JacoFingerVel_()
    : finger1Vel(0.0)
    , finger2Vel(0.0)
    , finger3Vel(0.0)  {
    }
  JacoFingerVel_(const ContainerAllocator& _alloc)
    : finger1Vel(0.0)
    , finger2Vel(0.0)
    , finger3Vel(0.0)  {
  (void)_alloc;
    }



   typedef float _finger1Vel_type;
  _finger1Vel_type finger1Vel;

   typedef float _finger2Vel_type;
  _finger2Vel_type finger2Vel;

   typedef float _finger3Vel_type;
  _finger3Vel_type finger3Vel;




  typedef boost::shared_ptr< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> const> ConstPtr;

}; // struct JacoFingerVel_

typedef ::wpi_jaco_msgs::JacoFingerVel_<std::allocator<void> > JacoFingerVel;

typedef boost::shared_ptr< ::wpi_jaco_msgs::JacoFingerVel > JacoFingerVelPtr;
typedef boost::shared_ptr< ::wpi_jaco_msgs::JacoFingerVel const> JacoFingerVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wpi_jaco_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wpi_jaco_msgs': ['/home/athomaz/vector_ws/src/wpi_jaco_msgs/msg', '/home/athomaz/vector_ws/devel/share/wpi_jaco_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a931e1014161865b6137e2ee19991131";
  }

  static const char* value(const ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa931e1014161865bULL;
  static const uint64_t static_value2 = 0x6137e2ee19991131ULL;
};

template<class ContainerAllocator>
struct DataType< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wpi_jaco_msgs/JacoFingerVel";
  }

  static const char* value(const ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 finger1Vel  # velocity for thumb\n\
float32 finger2Vel  # velocity for top finger\n\
float32 finger3Vel  # velocity for bottom finger\n\
";
  }

  static const char* value(const ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finger1Vel);
      stream.next(m.finger2Vel);
      stream.next(m.finger3Vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JacoFingerVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wpi_jaco_msgs::JacoFingerVel_<ContainerAllocator>& v)
  {
    s << indent << "finger1Vel: ";
    Printer<float>::stream(s, indent + "  ", v.finger1Vel);
    s << indent << "finger2Vel: ";
    Printer<float>::stream(s, indent + "  ", v.finger2Vel);
    s << indent << "finger3Vel: ";
    Printer<float>::stream(s, indent + "  ", v.finger3Vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WPI_JACO_MSGS_MESSAGE_JACOFINGERVEL_H
