// Generated by gencpp from file wpi_jaco_msgs/JacoFK.msg
// DO NOT EDIT!


#ifndef WPI_JACO_MSGS_MESSAGE_JACOFK_H
#define WPI_JACO_MSGS_MESSAGE_JACOFK_H

#include <ros/service_traits.h>


#include <wpi_jaco_msgs/JacoFKRequest.h>
#include <wpi_jaco_msgs/JacoFKResponse.h>


namespace wpi_jaco_msgs
{

struct JacoFK
{

typedef JacoFKRequest Request;
typedef JacoFKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JacoFK
} // namespace wpi_jaco_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wpi_jaco_msgs::JacoFK > {
  static const char* value()
  {
    return "c50123dac67d739b4055eead59e5c12f";
  }

  static const char* value(const ::wpi_jaco_msgs::JacoFK&) { return value(); }
};

template<>
struct DataType< ::wpi_jaco_msgs::JacoFK > {
  static const char* value()
  {
    return "wpi_jaco_msgs/JacoFK";
  }

  static const char* value(const ::wpi_jaco_msgs::JacoFK&) { return value(); }
};


// service_traits::MD5Sum< ::wpi_jaco_msgs::JacoFKRequest> should match 
// service_traits::MD5Sum< ::wpi_jaco_msgs::JacoFK > 
template<>
struct MD5Sum< ::wpi_jaco_msgs::JacoFKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wpi_jaco_msgs::JacoFK >::value();
  }
  static const char* value(const ::wpi_jaco_msgs::JacoFKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wpi_jaco_msgs::JacoFKRequest> should match 
// service_traits::DataType< ::wpi_jaco_msgs::JacoFK > 
template<>
struct DataType< ::wpi_jaco_msgs::JacoFKRequest>
{
  static const char* value()
  {
    return DataType< ::wpi_jaco_msgs::JacoFK >::value();
  }
  static const char* value(const ::wpi_jaco_msgs::JacoFKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wpi_jaco_msgs::JacoFKResponse> should match 
// service_traits::MD5Sum< ::wpi_jaco_msgs::JacoFK > 
template<>
struct MD5Sum< ::wpi_jaco_msgs::JacoFKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wpi_jaco_msgs::JacoFK >::value();
  }
  static const char* value(const ::wpi_jaco_msgs::JacoFKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wpi_jaco_msgs::JacoFKResponse> should match 
// service_traits::DataType< ::wpi_jaco_msgs::JacoFK > 
template<>
struct DataType< ::wpi_jaco_msgs::JacoFKResponse>
{
  static const char* value()
  {
    return DataType< ::wpi_jaco_msgs::JacoFK >::value();
  }
  static const char* value(const ::wpi_jaco_msgs::JacoFKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WPI_JACO_MSGS_MESSAGE_JACOFK_H
