(cl:in-package vector_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          WHEEL_MOTOR_STATUS-VAL
          WHEEL_MOTOR_STATUS
          WHEEL_MOTOR_CURRENT_A0PK-VAL
          WHEEL_MOTOR_CURRENT_A0PK
          WHEEL_MOTOR_SPEED_RPS-VAL
          WHEEL_MOTOR_SPEED_RPS
          WHEEL_MOTOR_POSITION_RAD-VAL
          WHEEL_MOTOR_POSITION_RAD
          LINEAR_MOTOR_STATUS-VAL
          LINEAR_MOTOR_STATUS
          LINEAR_MOTOR_CURRENT_A0PK-VAL
          LINEAR_MOTOR_CURRENT_A0PK
          LINEAR_MOTOR_SPEED_RPS-VAL
          LINEAR_MOTOR_SPEED_RPS
          LINEAR_MOTOR_POSITION_RAD-VAL
          LINEAR_MOTOR_POSITION_RAD
))