(cl:in-package vector_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          P_GAIN_RPS_PER_RPS-VAL
          P_GAIN_RPS_PER_RPS
          I_GAIN_RPS_PER_RAD-VAL
          I_GAIN_RPS_PER_RAD
          D_GAIN_RPS_PER_RPS2-VAL
          D_GAIN_RPS_PER_RPS2
          FDFWD_GAIN_RPS_PER_MOTOR_RPS-VAL
          FDFWD_GAIN_RPS_PER_MOTOR_RPS
          P_ERROR_LIMIT_RPS-VAL
          P_ERROR_LIMIT_RPS
          I_ERROR_LIMIT_RAD-VAL
          I_ERROR_LIMIT_RAD
          D_ERROR_LIMIT_RPS2-VAL
          D_ERROR_LIMIT_RPS2
          I_ERROR_DRAIN_RATE_RAD_PER_FRAME-VAL
          I_ERROR_DRAIN_RATE_RAD_PER_FRAME
          OUTPUT_LIMIT_RPS-VAL
          OUTPUT_LIMIT_RPS
          INPUT_TARGET_LIMIT_RPS-VAL
          INPUT_TARGET_LIMIT_RPS
          CONTROL_TUNING_UNLOCKED-VAL
          CONTROL_TUNING_UNLOCKED
))