// Generated by gencpp from file hlpr_knowledge_retrieval/ObjectKnowledge.msg
// DO NOT EDIT!


#ifndef HLPR_KNOWLEDGE_RETRIEVAL_MESSAGE_OBJECTKNOWLEDGE_H
#define HLPR_KNOWLEDGE_RETRIEVAL_MESSAGE_OBJECTKNOWLEDGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/String.h>
#include <hlpr_knowledge_retrieval/ObjectKnowledgeArray.h>

namespace hlpr_knowledge_retrieval
{
template <class ContainerAllocator>
struct ObjectKnowledge_
{
  typedef ObjectKnowledge_<ContainerAllocator> Type;

  ObjectKnowledge_()
    : header()
    , labels()
    , knowledge()  {
    }
  ObjectKnowledge_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , labels(_alloc)
    , knowledge(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::std_msgs::String_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::String_<ContainerAllocator> >::other >  _labels_type;
  _labels_type labels;

   typedef std::vector< ::hlpr_knowledge_retrieval::ObjectKnowledgeArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hlpr_knowledge_retrieval::ObjectKnowledgeArray_<ContainerAllocator> >::other >  _knowledge_type;
  _knowledge_type knowledge;




  typedef boost::shared_ptr< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectKnowledge_

typedef ::hlpr_knowledge_retrieval::ObjectKnowledge_<std::allocator<void> > ObjectKnowledge;

typedef boost::shared_ptr< ::hlpr_knowledge_retrieval::ObjectKnowledge > ObjectKnowledgePtr;
typedef boost::shared_ptr< ::hlpr_knowledge_retrieval::ObjectKnowledge const> ObjectKnowledgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hlpr_knowledge_retrieval

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'hlpr_knowledge_retrieval': ['/home/athomaz/vector_ws/src/hlpr_perception/hlpr_knowledge_retrieval/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24ebd4464299d72b0a523b08cac62371";
  }

  static const char* value(const ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24ebd4464299d72bULL;
  static const uint64_t static_value2 = 0x0a523b08cac62371ULL;
};

template<class ContainerAllocator>
struct DataType< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hlpr_knowledge_retrieval/ObjectKnowledge";
  }

  static const char* value(const ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
std_msgs/String[] labels\n\
ObjectKnowledgeArray[] knowledge\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: hlpr_knowledge_retrieval/ObjectKnowledgeArray\n\
std_msgs/String[] data\n\
";
  }

  static const char* value(const ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.labels);
      stream.next(m.knowledge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectKnowledge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hlpr_knowledge_retrieval::ObjectKnowledge_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "labels[]" << std::endl;
    for (size_t i = 0; i < v.labels.size(); ++i)
    {
      s << indent << "  labels[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "    ", v.labels[i]);
    }
    s << indent << "knowledge[]" << std::endl;
    for (size_t i = 0; i < v.knowledge.size(); ++i)
    {
      s << indent << "  knowledge[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hlpr_knowledge_retrieval::ObjectKnowledgeArray_<ContainerAllocator> >::stream(s, indent + "    ", v.knowledge[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HLPR_KNOWLEDGE_RETRIEVAL_MESSAGE_OBJECTKNOWLEDGE_H
