// Generated by gencpp from file hlpr_trac_ik/IKHandler.msg
// DO NOT EDIT!


#ifndef HLPR_TRAC_IK_MESSAGE_IKHANDLER_H
#define HLPR_TRAC_IK_MESSAGE_IKHANDLER_H

#include <ros/service_traits.h>


#include <hlpr_trac_ik/IKHandlerRequest.h>
#include <hlpr_trac_ik/IKHandlerResponse.h>


namespace hlpr_trac_ik
{

struct IKHandler
{

typedef IKHandlerRequest Request;
typedef IKHandlerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IKHandler
} // namespace hlpr_trac_ik


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hlpr_trac_ik::IKHandler > {
  static const char* value()
  {
    return "9aa495ca2916258a4ba1dba1ad308475";
  }

  static const char* value(const ::hlpr_trac_ik::IKHandler&) { return value(); }
};

template<>
struct DataType< ::hlpr_trac_ik::IKHandler > {
  static const char* value()
  {
    return "hlpr_trac_ik/IKHandler";
  }

  static const char* value(const ::hlpr_trac_ik::IKHandler&) { return value(); }
};


// service_traits::MD5Sum< ::hlpr_trac_ik::IKHandlerRequest> should match 
// service_traits::MD5Sum< ::hlpr_trac_ik::IKHandler > 
template<>
struct MD5Sum< ::hlpr_trac_ik::IKHandlerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hlpr_trac_ik::IKHandler >::value();
  }
  static const char* value(const ::hlpr_trac_ik::IKHandlerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hlpr_trac_ik::IKHandlerRequest> should match 
// service_traits::DataType< ::hlpr_trac_ik::IKHandler > 
template<>
struct DataType< ::hlpr_trac_ik::IKHandlerRequest>
{
  static const char* value()
  {
    return DataType< ::hlpr_trac_ik::IKHandler >::value();
  }
  static const char* value(const ::hlpr_trac_ik::IKHandlerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hlpr_trac_ik::IKHandlerResponse> should match 
// service_traits::MD5Sum< ::hlpr_trac_ik::IKHandler > 
template<>
struct MD5Sum< ::hlpr_trac_ik::IKHandlerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hlpr_trac_ik::IKHandler >::value();
  }
  static const char* value(const ::hlpr_trac_ik::IKHandlerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hlpr_trac_ik::IKHandlerResponse> should match 
// service_traits::DataType< ::hlpr_trac_ik::IKHandler > 
template<>
struct DataType< ::hlpr_trac_ik::IKHandlerResponse>
{
  static const char* value()
  {
    return DataType< ::hlpr_trac_ik::IKHandler >::value();
  }
  static const char* value(const ::hlpr_trac_ik::IKHandlerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HLPR_TRAC_IK_MESSAGE_IKHANDLER_H
