(cl:defpackage rail_manipulation_msgs-srv
  (:use )
  (:export
   "CARTESIANPATH"
   "<CARTESIANPATH-REQUEST>"
   "CARTESIANPATH-REQUEST"
   "<CARTESIANPATH-RESPONSE>"
   "CARTESIANPATH-RESPONSE"
   "PREPAREGRASP"
   "<PREPAREGRASP-REQUEST>"
   "PREPAREGRASP-REQUEST"
   "<PREPAREGRASP-RESPONSE>"
   "PREPAREGRASP-RESPONSE"
   "CALLIK"
   "<CALLIK-REQUEST>"
   "CALLIK-REQUEST"
   "<CALLIK-RESPONSE>"
   "CALLIK-RESPONSE"
  ))

