// Generated by gencpp from file task3/object_frame_data.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_OBJECT_FRAME_DATA_H
#define TASK3_MESSAGE_OBJECT_FRAME_DATA_H

#include <ros/service_traits.h>


#include <task3/object_frame_dataRequest.h>
#include <task3/object_frame_dataResponse.h>


namespace task3
{

struct object_frame_data
{

typedef object_frame_dataRequest Request;
typedef object_frame_dataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct object_frame_data
} // namespace task3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task3::object_frame_data > {
  static const char* value()
  {
    return "d3812c3cbc69362b77dc0b19b345f8f5";
  }

  static const char* value(const ::task3::object_frame_data&) { return value(); }
};

template<>
struct DataType< ::task3::object_frame_data > {
  static const char* value()
  {
    return "task3/object_frame_data";
  }

  static const char* value(const ::task3::object_frame_data&) { return value(); }
};


// service_traits::MD5Sum< ::task3::object_frame_dataRequest> should match 
// service_traits::MD5Sum< ::task3::object_frame_data > 
template<>
struct MD5Sum< ::task3::object_frame_dataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task3::object_frame_data >::value();
  }
  static const char* value(const ::task3::object_frame_dataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::object_frame_dataRequest> should match 
// service_traits::DataType< ::task3::object_frame_data > 
template<>
struct DataType< ::task3::object_frame_dataRequest>
{
  static const char* value()
  {
    return DataType< ::task3::object_frame_data >::value();
  }
  static const char* value(const ::task3::object_frame_dataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task3::object_frame_dataResponse> should match 
// service_traits::MD5Sum< ::task3::object_frame_data > 
template<>
struct MD5Sum< ::task3::object_frame_dataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task3::object_frame_data >::value();
  }
  static const char* value(const ::task3::object_frame_dataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::object_frame_dataResponse> should match 
// service_traits::DataType< ::task3::object_frame_data > 
template<>
struct DataType< ::task3::object_frame_dataResponse>
{
  static const char* value()
  {
    return DataType< ::task3::object_frame_data >::value();
  }
  static const char* value(const ::task3::object_frame_dataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK3_MESSAGE_OBJECT_FRAME_DATA_H
