// Generated by gencpp from file hlpr_perception_msgs/ColorHist.msg
// DO NOT EDIT!


#ifndef HLPR_PERCEPTION_MSGS_MESSAGE_COLORHIST_H
#define HLPR_PERCEPTION_MSGS_MESSAGE_COLORHIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hlpr_perception_msgs
{
template <class ContainerAllocator>
struct ColorHist_
{
  typedef ColorHist_<ContainerAllocator> Type;

  ColorHist_()
    : hs_features_size(0)
    , hs_feature_vector()  {
    }
  ColorHist_(const ContainerAllocator& _alloc)
    : hs_features_size(0)
    , hs_feature_vector(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _hs_features_size_type;
  _hs_features_size_type hs_features_size;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _hs_feature_vector_type;
  _hs_feature_vector_type hs_feature_vector;




  typedef boost::shared_ptr< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> const> ConstPtr;

}; // struct ColorHist_

typedef ::hlpr_perception_msgs::ColorHist_<std::allocator<void> > ColorHist;

typedef boost::shared_ptr< ::hlpr_perception_msgs::ColorHist > ColorHistPtr;
typedef boost::shared_ptr< ::hlpr_perception_msgs::ColorHist const> ColorHistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hlpr_perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'hlpr_perception_msgs': ['/home/athomaz/vector_ws/src/hlpr_perception/hlpr_perception_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ebad72734bb047d4755073dfeadac24";
  }

  static const char* value(const ::hlpr_perception_msgs::ColorHist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ebad72734bb047dULL;
  static const uint64_t static_value2 = 0x4755073dfeadac24ULL;
};

template<class ContainerAllocator>
struct DataType< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hlpr_perception_msgs/ColorHist";
  }

  static const char* value(const ::hlpr_perception_msgs::ColorHist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Hue-Saturation histogram\n\
\n\
uint32 hs_features_size\n\
float64[] hs_feature_vector\n\
\n\
";
  }

  static const char* value(const ::hlpr_perception_msgs::ColorHist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hs_features_size);
      stream.next(m.hs_feature_vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorHist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hlpr_perception_msgs::ColorHist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hlpr_perception_msgs::ColorHist_<ContainerAllocator>& v)
  {
    s << indent << "hs_features_size: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.hs_features_size);
    s << indent << "hs_feature_vector[]" << std::endl;
    for (size_t i = 0; i < v.hs_feature_vector.size(); ++i)
    {
      s << indent << "  hs_feature_vector[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.hs_feature_vector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HLPR_PERCEPTION_MSGS_MESSAGE_COLORHIST_H
