// Generated by gencpp from file hlpr_perception_msgs/ExtractedFeaturesArray.msg
// DO NOT EDIT!


#ifndef HLPR_PERCEPTION_MSGS_MESSAGE_EXTRACTEDFEATURESARRAY_H
#define HLPR_PERCEPTION_MSGS_MESSAGE_EXTRACTEDFEATURESARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hlpr_perception_msgs/ObjectFeatures.h>
#include <hlpr_perception_msgs/PlaneFeatures.h>
#include <geometry_msgs/Transform.h>

namespace hlpr_perception_msgs
{
template <class ContainerAllocator>
struct ExtractedFeaturesArray_
{
  typedef ExtractedFeaturesArray_<ContainerAllocator> Type;

  ExtractedFeaturesArray_()
    : header()
    , objects()
    , planes()
    , transforms()  {
    }
  ExtractedFeaturesArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)
    , planes(_alloc)
    , transforms(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::hlpr_perception_msgs::ObjectFeatures_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hlpr_perception_msgs::ObjectFeatures_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;

   typedef std::vector< ::hlpr_perception_msgs::PlaneFeatures_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hlpr_perception_msgs::PlaneFeatures_<ContainerAllocator> >::other >  _planes_type;
  _planes_type planes;

   typedef std::vector< ::geometry_msgs::Transform_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Transform_<ContainerAllocator> >::other >  _transforms_type;
  _transforms_type transforms;




  typedef boost::shared_ptr< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> const> ConstPtr;

}; // struct ExtractedFeaturesArray_

typedef ::hlpr_perception_msgs::ExtractedFeaturesArray_<std::allocator<void> > ExtractedFeaturesArray;

typedef boost::shared_ptr< ::hlpr_perception_msgs::ExtractedFeaturesArray > ExtractedFeaturesArrayPtr;
typedef boost::shared_ptr< ::hlpr_perception_msgs::ExtractedFeaturesArray const> ExtractedFeaturesArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hlpr_perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'hlpr_perception_msgs': ['/home/athomaz/vector_ws/src/hlpr_perception/hlpr_perception_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d19ef1ccb2fc5e726ee96ccb7f68a2e6";
  }

  static const char* value(const ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd19ef1ccb2fc5e72ULL;
  static const uint64_t static_value2 = 0x6ee96ccb7f68a2e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hlpr_perception_msgs/ExtractedFeaturesArray";
  }

  static const char* value(const ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Features for a single cluster\n\
\n\
Header header\n\
ObjectFeatures[] objects\n\
PlaneFeatures[] planes \n\
geometry_msgs/Transform[] transforms\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: hlpr_perception_msgs/ObjectFeatures\n\
# Features for a single object cluster\n\
\n\
Header header\n\
\n\
geometry_msgs/Transform transform\n\
\n\
BasicFeatures basicInfo\n\
OrientedBoundingBox obb\n\
\n\
bool setColorHist            # Flag to state if hs_hist was computed and set (default=true)\n\
ColorHist hs_hist\n\
\n\
bool setShapeHist            # Flag to state if shape_hist was computed and set (default=true)\n\
ShapeHist shape_hist\n\
\n\
bool setViewpointHist        # Flag to state if view_hist was computed and set (default=true)\n\
ViewpointHist view_hist\n\
\n\
bool setOtherFeatures        # Flag to state if other features were computed and set (default=false)\n\
OtherFeatures other\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Transform\n\
# This represents the transform between two coordinate frames in free space.\n\
\n\
Vector3 translation\n\
Quaternion rotation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: hlpr_perception_msgs/BasicFeatures\n\
# Raw point Related\n\
\n\
# Cluster centroid, min, max and number of points\n\
geometry_msgs/Vector3 points_centroid\n\
geometry_msgs/Vector3 points_min   #<pc min x, pc min y, pc min z>\n\
geometry_msgs/Vector3 points_max   #<pc max x, pc max y, pc max z>\n\
\n\
bool setNumPoints                # flag is required for planes as they only have contours, \n\
float64 num_points               # the num_points is not applicable to planes\n\
\n\
# Average color (RGBA and hue)\n\
std_msgs/ColorRGBA rgba_color\n\
float64 hue\n\
\n\
================================================================================\n\
MSG: std_msgs/ColorRGBA\n\
float32 r\n\
float32 g\n\
float32 b\n\
float32 a\n\
\n\
================================================================================\n\
MSG: hlpr_perception_msgs/OrientedBoundingBox\n\
#Oriented Bounding box\n\
\n\
#position wrt sensor \n\
geometry_msgs/Vector3 bb_center\n\
\n\
# Bounding box dimensions\n\
geometry_msgs/Vector3 bb_dims\n\
\n\
#Bounding box quaternion\n\
geometry_msgs/Quaternion bb_rot_quat\n\
\n\
================================================================================\n\
MSG: hlpr_perception_msgs/ColorHist\n\
# Hue-Saturation histogram\n\
\n\
uint32 hs_features_size\n\
float64[] hs_feature_vector\n\
\n\
\n\
================================================================================\n\
MSG: hlpr_perception_msgs/ShapeHist\n\
# Shape histogram using CVFH\n\
\n\
uint32 cvfh_features_size\n\
float64[] cvfh_feature_vector\n\
\n\
#################################\n\
# Shape histogram using FPFH\n\
\n\
uint32 fpfh_features_size\n\
float64[] fpfh_feature_vector\n\
\n\
================================================================================\n\
MSG: hlpr_perception_msgs/ViewpointHist\n\
# VFH features\n\
\n\
uint32 vfh_features_size\n\
float64[] vfh_feature_vector\n\
\n\
\n\
================================================================================\n\
MSG: hlpr_perception_msgs/OtherFeatures\n\
#Other features, etc. Unpacking will be on the other side\n\
\n\
uint32 other_features_size\n\
float64[] data\n\
\n\
================================================================================\n\
MSG: hlpr_perception_msgs/PlaneFeatures\n\
# Features for a single plane cluster\n\
\n\
Header header\n\
BasicFeatures basicInfo\n\
OrientedBoundingBox obb\n\
";
  }

  static const char* value(const ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
      stream.next(m.planes);
      stream.next(m.transforms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExtractedFeaturesArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hlpr_perception_msgs::ExtractedFeaturesArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hlpr_perception_msgs::ObjectFeatures_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
    s << indent << "planes[]" << std::endl;
    for (size_t i = 0; i < v.planes.size(); ++i)
    {
      s << indent << "  planes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hlpr_perception_msgs::PlaneFeatures_<ContainerAllocator> >::stream(s, indent + "    ", v.planes[i]);
    }
    s << indent << "transforms[]" << std::endl;
    for (size_t i = 0; i < v.transforms.size(); ++i)
    {
      s << indent << "  transforms[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "    ", v.transforms[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HLPR_PERCEPTION_MSGS_MESSAGE_EXTRACTEDFEATURESARRAY_H
