// Generated by gencpp from file hlpr_perception_msgs/OtherFeatures.msg
// DO NOT EDIT!


#ifndef HLPR_PERCEPTION_MSGS_MESSAGE_OTHERFEATURES_H
#define HLPR_PERCEPTION_MSGS_MESSAGE_OTHERFEATURES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hlpr_perception_msgs
{
template <class ContainerAllocator>
struct OtherFeatures_
{
  typedef OtherFeatures_<ContainerAllocator> Type;

  OtherFeatures_()
    : other_features_size(0)
    , data()  {
    }
  OtherFeatures_(const ContainerAllocator& _alloc)
    : other_features_size(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _other_features_size_type;
  _other_features_size_type other_features_size;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> const> ConstPtr;

}; // struct OtherFeatures_

typedef ::hlpr_perception_msgs::OtherFeatures_<std::allocator<void> > OtherFeatures;

typedef boost::shared_ptr< ::hlpr_perception_msgs::OtherFeatures > OtherFeaturesPtr;
typedef boost::shared_ptr< ::hlpr_perception_msgs::OtherFeatures const> OtherFeaturesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hlpr_perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'hlpr_perception_msgs': ['/home/athomaz/vector_ws/src/hlpr_perception/hlpr_perception_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d22cbac6bc3cfd07bc3aeb056714914";
  }

  static const char* value(const ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d22cbac6bc3cfd0ULL;
  static const uint64_t static_value2 = 0x7bc3aeb056714914ULL;
};

template<class ContainerAllocator>
struct DataType< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hlpr_perception_msgs/OtherFeatures";
  }

  static const char* value(const ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Other features, etc. Unpacking will be on the other side\n\
\n\
uint32 other_features_size\n\
float64[] data\n\
";
  }

  static const char* value(const ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.other_features_size);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OtherFeatures_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hlpr_perception_msgs::OtherFeatures_<ContainerAllocator>& v)
  {
    s << indent << "other_features_size: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.other_features_size);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HLPR_PERCEPTION_MSGS_MESSAGE_OTHERFEATURES_H
